In [1]:
import awkward as ak
import numpy as np
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema
from coffea import processor, hist

fname = "https://raw.githubusercontent.com/CoffeaTeam/coffea/master/tests/samples/nano_dy.root"
events = NanoEventsFactory.from_root(fname, schemaclass=NanoAODSchema).events()

/Users/eddie/opt/miniconda3/envs/topcoffea-env/lib/python3.8/site-packages/coffea/nanoevents/schemas/nanoaod.py:193: RuntimeWarning: Missing cross-reference index for FatJet_genJetAK8Idx => GenJetAK8
  warnings.warn(


In [2]:
leptons = 3
charge = None
jets = 4

In [3]:
if charge != None:
    filt_events = events[
        ((ak.num(events.Electron) + ak.num(events.Muon)) == leptons) &
        ((ak.sum(events.Electron.charge, axis=1)) + (ak.sum(events.Muon.charge, axis=1)) == charge) &
        (ak.num(events.Jet) == jets)]
else: 
    filt_events = events[
        ((ak.num(events.Electron) + ak.num(events.Muon)) == leptons) &
        (ak.num(events.Jet) == jets)]

In [4]:
print(filt_events)

[<event 1:13889:3749781>]


In [5]:
jet_4_vec = np.array(
    [
        np.squeeze(ak.to_numpy(filt_events.Jet.pt)),
        np.squeeze(ak.to_numpy(filt_events.Jet.eta)),
        np.squeeze(ak.to_numpy(filt_events.Jet.phi)),
        np.squeeze(ak.to_numpy(filt_events.Jet.mass))
    ]
)

mu_4_vec = np.array(
    [
        np.squeeze(ak.to_numpy(filt_events.Muon.pt)),
        np.squeeze(ak.to_numpy(filt_events.Muon.eta)),
        np.squeeze(ak.to_numpy(filt_events.Muon.phi)),
        np.squeeze(ak.to_numpy(filt_events.Muon.mass))
    ]
)


el_4_vec = np.array(
    [
        np.squeeze(ak.to_numpy(filt_events.Electron.pt)),
        np.squeeze(ak.to_numpy(filt_events.Electron.eta)),
        np.squeeze(ak.to_numpy(filt_events.Electron.phi)),
        np.squeeze(ak.to_numpy(filt_events.Electron.mass))
    ]
)
lep_4_vec = np.c_[el_4_vec, mu_4_vec]

In [6]:
print(jet_4_vec)
print(mu_4_vec)
print(el_4_vec)
print(lep_4_vec)

[[81.875      53.375      38.03125    25.296875  ]
 [-2.083496    0.09056091 -4.301758   -3.4301758 ]
 [-2.7475586   0.47424316 -0.7056885   1.217041  ]
 [ 9.4921875   0.11138916  7.0507812   4.9648438 ]]
[[50.641342   14.330103  ]
 [ 0.09056091 -2.0439453 ]
 [ 0.47424316 -2.6386719 ]
 [ 0.10571289  0.10571289]]
[33.151806   -2.1044922  -2.819336   -0.03338623]
[[ 3.3151806e+01  5.0641342e+01  1.4330103e+01]
 [-2.1044922e+00  9.0560913e-02 -2.0439453e+00]
 [-2.8193359e+00  4.7424316e-01 -2.6386719e+00]
 [-3.3386230e-02  1.0571289e-01  1.0571289e-01]]
